---
title: "Untitled"
author: "jessi潘"
date: "2017年10月3日"
output: word_document
---
#数据框#
```{r}
x<-10:1
y<--4:5
q<-c("Hockey","Football","Baseball","Curling","Rugby","Lacrosse","Basketball","Tennis","Cricket","Soccer")
theDF<-data.frame(x,y,q)#建立数据框#
theDF
```
```{r}
theDF<-data.frame(First=x,Second=y,Sport=q)#names(theDF)<-c("First","Second","Sport")#
theDF
```
```{r}
nrow(theDF)#行数#
ncol(theDF)#列数#
dim(theDF)#行列数#
names(theDF)#列表清单#
names(theDF)[2]
rownames(theDF)
rownames(theDF)<-c("one","two","three","four","five","six","seven","eight","nine","ten")
theDF

```

```{r}
head(theDF,n=2)#显示前面几行#
tail(theDF)
theDF$Sport#$访问其中一列#
theDF[3,2]#第一个代表行数，第二个代表列数#
theDF[c(3,5),2:3]
theDF[,2:3]#整行#
theDF[,c("First","Sport")]
theDF[,"Sport"]
theDF[["Sport"]]
class(theDF[["Sport"]])
theDF[,"Sport",drop=FALSE]#确保输出的一个单列的数据框#
```

```{r}
newfactor<-factor(c("Pennsylvania","New York","New Jersey","New York","Tennessee","Massachusetts","Pennsylvania","New York"))
model.matrix(~newfactor-1)#创建一个指示性变量（或哑变量）的集合#
```
#list 创建，函数的每一个参数变成列表的参数#
```{r}
list(1,2,3)
```

```{r}
list(c(1,2,3))
list(1:3)
list3<-list(c(1,2,3),3:7,1)#建立两个列表#
list3
```

```{r}
x<-10:1
y<--4:5
q<-c("Hockey","Football","Baseball","Curling","Rugby","Lacrosse","Basketball","Tennis","Cricket","Soccer")
theDF<-data.frame(x,y,q)#建立数据框#
theDF
theDF<-data.frame(First=x,Second=y,Sport=q)
theDF
```

```{r}
list(theDF,1:10)
list5<-list(theDF,1:10,list3)
names(list5)<-c("data.frame","vector","list")
names(list5)
list5
list6<-list(thedatafram=theDF,thevector=1:10,thelist=list3)
names(list6)
list6
emptylist<-vector(mode="list",length = 4)#创建一个长度为4的空列表
list5[[1]]
list5[["data.frame"]]
list5[[1]]$Sport#实际使用的元素在一个被访问的元素中#
list5[[1]][,"Second"]
list5[[1]][,"Second",drop=FALSE]
length(list5)
list5[[4]]<-2#增加列表元素#
length(list5)
list5[["newelements"]]<-3:6
length(list5)
names(list5)
list5

```
#矩阵#
```{r}
A<-matrix(1:10,nrow=5,byrow = T)
B<-matrix(21:30,nrow=5)
C<-matrix(21:40,nrow = 2)#矩阵行#
A
B
C
```

```{r}
nrow(A)#行数#
ncol(A)#列数#
dim(A)#行列数#
A+B
A*B
A==B
```
#矩阵乘法要求左边矩阵的列数等于右边矩阵的行数，所以矩阵A和B都是5*2的矩阵们需要左边的矩阵进行转置后才能进行计算#
```{r}
A%*%t(B)
colnames(A)##矩阵的列的名字
colnames(A)<-c("left","right")
rownames(A)<-c("1st","2st","3st","4st","5st")
colnames(B)<-c("first","second")
rownames(B)<-c("one","two","three","four","five")
colnames(C)<-LETTERS[1:10]#大写字母#
rownames(C)<-c("Top","Bottom")
A%*%C
C
```
#数组（所有元素必须类型相同）#
```{r}
thearray<-array(1:12,dim=c(2,3,2))#行，列,#
thearray
thearray[1,,]#第一个数是行指标，第二个是列指标,#
thearray[1,,1]
thearray[,,1]#第1维#
```

